import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '/JoyCode2Api/',
  title: 'JoyCode API 代理 — 协议翻译成 Anthropic/OpenAI 兼容格式，让 Claude Code 直接调用 JoyCode支持的模型，比如GLM 5.1等',
  description: 'JoyCode API 代理 — 协议翻译成 Anthropic/OpenAI 兼容格式，让 Claude Code 直接调用 JoyCode支持的模型，比如GLM 5.1等',
  lang: 'zh-CN',
  lastUpdated: true,
  ignoreDeadLinks: true,
  markdown: {
    lineNumbers: true,
  },
  themeConfig: {
    search: {
      provider: 'local',
    },
    nav: [
      { text: '文档首页', link: '/' },
      { text: 'GitHub', link: 'https://github.com/vibe-coding-labs/JoyCode2Api' },
    ],
    sidebar: [
          { text: "JoyCode API 代理 — 协议翻译成 Anthropic/Open...", items: [
            { text: "首页", link: "/" },
            { text: "Claude Code Protocol Optimization Plan", link: "/superpowers/plans/2026-04-27-claude-code-protocol-optimization" },
            { text: "CLI UI Enhancement Plan", link: "/superpowers/plans/2026-04-27-cli-ui-enhancement" },
            { text: "Credential Validation on Startup Implementation Plan", link: "/superpowers/plans/2026-04-27-credential-validation" },
            { text: "Go to Python Rewrite Plan", link: "/superpowers/plans/2026-04-27-go-to-python-rewrite" },
            { text: "Account Detail Page & Model Configuration", link: "/superpowers/plans/2026-04-28-account-detail-page" },
            { text: "凭证加密 + 前端优化 + 设置页增强 Implementation Plan", link: "/superpowers/plans/2026-04-28-encryption-frontend-settings" },
            { text: "Multi-Account Credential Routing Plan", link: "/superpowers/plans/2026-04-28-multi-account-credential-routing" },
            { text: "Web Dashboard Implementation Plan", link: "/superpowers/plans/2026-04-28-web-dashboard" },
            { text: "Go CLI 命令补全 Implementation Plan", link: "/superpowers/plans/2026-04-29-cli-completion" },
            { text: "CLI UX 精细化 Implementation Plan", link: "/superpowers/plans/2026-04-29-cli-ux-polish" },
            { text: "JD Account Login Integration Plan", link: "/superpowers/plans/2026-04-29-jd-login-integration" },
            { text: "Backend Unification QA & Cleanup Plan", link: "/superpowers/plans/2026-04-30-backend-unification-qa" },
            { text: "Cross-Platform Service & Daemon Mode Implementation Plan", link: "/superpowers/plans/2026-04-30-cross-platform-daemon-service" },
            { text: "Error Detection and Logging Enhancement Plan", link: "/superpowers/plans/2026-04-30-error-detection-logging-v2" },
            { text: "Structured Error Logging Implementation Plan", link: "/superpowers/plans/2026-04-30-structured-error-logging" },
            { text: "Dashboard 一键登录实现 Plan", link: "/superpowers/plans/2026-05-01-dashboard-auto-login" },
            { text: "Accounts 行点击导航修复 + 命令预览 Tooltip 实现 Plan", link: "/superpowers/plans/2026-05-02-accounts-row-click-and-command-tooltip" },
            { text: "代理层自动上下文截断 — 解决上下文超限死循环", link: "/superpowers/plans/2026-05-02-auto-context-truncation" },
            { text: "修复: 上下文超限导致客户端无限重试", link: "/superpowers/plans/2026-05-02-context-window-exceeded-fix" },
            { text: "Dashboard 数据准确性优化 Implementation Plan", link: "/superpowers/plans/2026-05-02-dashboard-data-accuracy" },
            { text: "Dashboard QR 码扫码登录实现 Plan", link: "/superpowers/plans/2026-05-02-dashboard-qr-login" },
            { text: "Dashboard 大屏重设计 + 路由独立化 Implementation Plan", link: "/superpowers/plans/2026-05-02-dashboard-redesign" },
            { text: "Bug Fix: 错误日志详情 + 日志增强", link: "/superpowers/plans/2026-05-02-error-detail-and-log-improvements" },
            { text: "Fix QR Login Polling — 扫码确认后前端无响应", link: "/superpowers/plans/2026-05-02-qr-login-polling-fix" },
            { text: "Settings Page Audit & Green Theme Fix", link: "/superpowers/plans/2026-05-02-settings-audit-and-theme" },
            { text: "Settings Page: Wire All \"规划中\" Settings Implementation Plan", link: "/superpowers/plans/2026-05-02-settings-implementation" },
            { text: "Sidebar Green Theme & Remove Broken QR Login", link: "/superpowers/plans/2026-05-02-sidebar-green-theme-and-remove-broken-qr" },
            { text: "Fix Tool Call Parsing Failure Implementation Plan", link: "/superpowers/plans/2026-05-02-tool-call-parsing-fix" },
            { text: "AccountDetail 统计面板增强 Implementation Plan", link: "/superpowers/plans/2026-05-03-account-detail-stats-panels" },
            { text: "Account Keep-Alive (账号凭证保活机制) Implementation Plan", link: "/superpowers/plans/2026-05-03-account-keepalive" },
            { text: "Account Stats 24h Dimension Implementation Plan", link: "/superpowers/plans/2026-05-03-account-stats-24h-dimension" },
            { text: "Feature: JoyCode 浏览器 OAuth 回调登录 — 构建多账号池", link: "/superpowers/plans/2026-05-03-joycode-browser-oauth-login" },
            { text: "Bug Fix: pt_key cookie not found after QR validation", link: "/superpowers/plans/2026-05-03-pt-key-cookie-not-found-fix" },
            { text: "Bug Fix: QR login pt_key extraction — JD 不再通过 Set-Cookie 返回 pt_key", link: "/superpowers/plans/2026-05-03-qr-login-ptkey-extraction-v2" },
            { text: "Bug Fix: QR 登录 pt_key 提取失败 — 改为一键登录优先策略", link: "/superpowers/plans/2026-05-03-qr-login-redirect-to-auto-login" },
            { text: "UserID Masking & Active Session Counting Plan", link: "/superpowers/plans/2026-05-03-userid-mask-active-sessions" },
            { text: "Log Rotation & Enhanced Logging Implementation Plan", link: "/superpowers/plans/2026-05-13-log-rotation" },
            { text: "Log Safety Hardening & Enhanced Communication Logging", link: "/superpowers/plans/2026-05-13-log-safety-hardening" },
            { text: "Bug Fix: 流式超时丢 tool 参数 + content_filter 未处理 + 截断破坏 tool 消息对", link: "/superpowers/plans/2026-05-13-stream-error-tool-drop-fix" },
            { text: "Account Export/Import Implementation Plan", link: "/superpowers/plans/2026-05-18-account-export-import" },
            { text: "Bug Fix: SPA Catch-All Intercepts API Requests Without `/v1` Prefix", link: "/superpowers/plans/2026-05-20-spa-catchall-api-fix" },
            { text: "Account Name Column Width + Import Dedup Fix", link: "/superpowers/plans/2026-06-04-account-ui-import-dedup" },
          ] }
        ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vibe-coding-labs/JoyCode2Api' },
    ],
    footer: {
      message: '基于 VitePress 构建',
    },
  },
})
